version: '3.8'

services:
  server:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    ports:
      - 8100:8100

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.1
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    command: ["start-dev"]