version: '3.8'

services:
  server:
    build:
      dockerfile: dev/Dockerfile-server
    environment:
      HADOOP_CONF_DIR: /usr/src/app/dev
    volumes:
      - .:/usr/src/app
      - cargo:/usr/local/cargo/registry/
      - staging:/staging
    command: ["cargo", "run", "--", "-c", "conf/config.yaml"]
    ports:
      - 8100:8100

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    profiles:
      - db

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.1
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    command: ["start-dev"]
    profiles:
      - keycloak

  resourcemanager:
    image: spark-connect-proxy-hadoop
    build:
      dockerfile: dev/Dockerfile-hadoop
    ports:
      - 8088:8088
      - 8030-8033:8030-8033
    volumes:
      - ./dev/yarn-site.xml:/opt/hadoop-3.4.1/etc/hadoop/yarn-site.xml
      - staging:/staging
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    profiles:
      - hadoop

  nodemanager:
    image: spark-connect-proxy-hadoop
    build:
      dockerfile: dev/Dockerfile-hadoop
    ports:
      - 8042:8042
    volumes:
      - ./dev/yarn-site.xml:/opt/hadoop-3.4.1/etc/hadoop/yarn-site.xml
      - staging:/staging
    hostname: nodemanager
    command: ["yarn", "nodemanager"]
    profiles:
      - hadoop

  # Uses internal image based on 2.0.0 release
  knox-custom:
    build:
      dockerfile: dev/Dockerfile-knox
    environment:
      KNOX_GATEWAY_RUNNING_IN_FOREGROUND: "true"
    ports:
      - 8443:8443
    volumes:
      - ./dev/knox/knox-entrypoint.sh:/entrypoint.sh
      - ./dev/knox/topologies:/opt/knox/conf/topologies
      - ./dev/knox/gateway-log4j2.xml:/opt/knox/conf/gateway-log4j2.xml
      - ./dev/knox/gateway-site.xml:/opt/knox/conf/gateway-site.xml
    entrypoint: ["/entrypoint.sh"]
    command: ["./bin/gateway.sh", "start"]
    profiles:
      - knox-custom

  # Used to test master Knox code
  # To build this, run `mvn -Ppackage -Pdocker clean install -DskipTests -Ddocker.platforms=""`
  # Needs Java 8 to build
  knox-master:
    image: knox-gateway:2.1.0-SNAPSHOT
    ports:
      - 8443:8443
    volumes:
      - ./dev/knox/topologies:/home/knox/knox/conf/topologies
      - ./dev/knox/gateway-log4j2.xml:/home/knox/knox/conf/gateway-log4j2.xml
      - ./dev/knox/gateway-site.xml:/home/knox/knox/conf/gateway-site.xml
    profiles:
      - knox-master

volumes:
  cargo:
  staging: